feat(bootstrap): custom gtag.js url
MatteoGabriele/vue-gtag pull request #177
Opened 2020-08-27 18:34 UTC by Yihao-G

Allow users to customise gtag.js URL.

Fixes #167

2020-09-01 19:20 UTC, MatteoGabriele requested changes
thanks for the contribution

2020-09-01 19:20 UTC, MatteoGabriele commented on src/bootstrap.js
> +  const domain = new URL(customResourceURL).origin;
unfortunately the URL api is not supported by IE

2020-09-02 10:19 UTC, Yihao-G commented
Finally, so many strict checks and linters 😂

2020-09-02 13:13 UTC, MatteoGabriele commented
wow. thanks for your work but it seems like this `getUrlOrigin` is almost as long as the entire plugin itself ahahahahha
what about just going with a default domain value, as the gtag one, and then make it available for users to change it accordingly?

2020-09-02 14:27 UTC, Yihao-G commented
How about this one now?

2020-09-02 14:34 UTC, MatteoGabriele approved these changes
looking good! thanks a lot for sorting this out!

2020-09-02 14:35 UTC, merged

2020-09-02 14:40 UTC, MatteoGabriele commented
:tada: This PR is included in version 1.9.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/vue-gtag)
- [GitHub release](https://github.com/MatteoGabriele/vue-gtag/releases/tag/v1.9.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: